import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-sky-channels',
  templateUrl: './component.html',
  styleUrls: ['./component.scss'],
})
export class SkyChannelsComponent implements OnInit {
  searchText = '';

  channels = [
    { id: 1, name: 'Das Erste HD ' },
    { id: 2, name: 'ZDF HD' },
    { id: 3, name: 'RTL Television ' },
    { id: 4, name: 'SAT.1' },
    { id: 5, name: 'VOX' },
    { id: 6, name: 'ProSieben ' },
    { id: 7, name: 'kabel eins ' },
    { id: 8, name: 'RTL2' },
    { id: 9, name: 'zdf_neo HD' },
    { id: 10, name: 'WDR HD Köln' },
    { id: 11, name: 'BR FS Süd HD' },
    { id: 12, name: 'SUPER RTL' },
    { id: 13, name: 'NITRO' },
    { id: 14, name: 'NDR FS NDS HD' },
    { id: 15, name: 'SAT.1 Gold' },
    { id: 16, name: '3sat HD' },
    { id: 17, name: 'MDR S-Anhalt HD' },
    { id: 18, name: 'ZDFinfo HD' },
    { id: 19, name: 'RTLplus' },
    { id: 20, name: 'arte HD' },
    { id: 21, name: 'n-tv' },
    { id: 22, name: 'hr-fernsehen HD' },
    { id: 23, name: 'PHOENIX HD' },
    { id: 24, name: 'rbb Berlin HD' },
    { id: 25, name: 'KiKA HD' },
    { id: 26, name: 'DMAX' },
    { id: 27, name: 'WELT' },
    { id: 28, name: 'SWR BW HD' },
    { id: 29, name: 'Disney Channel' },
    { id: 30, name: 'SPORT 1' },
    { id: 31, name: 'TELE 5' },
    { id: 32, name: 'SIXX' },
    { id: 33, name: 'Pro7 MAXX' },
    { id: 34, name: 'SWR RP HD' },
    { id: 35, name: 'ONE HD' },
    { id: 36, name: 'Eurosport 1 DE' },
    { id: 37, name: 'MDR Sachsen HD' },
    { id: 38, name: 'kabel eins Doku' },
    { id: 39, name: 'TLC' },
    { id: 40, name: 'tagesschau24 HD' },
    { id: 41, name: 'Servus TV HD DE' },
    { id: 42, name: 'Radio Bremen TV' },
    { id: 43, name: 'DELUXE MUSIC' },
    { id: 44, name: 'NDR FS HH HD' },
    { id: 45, name: 'rbb BrandenburgHD' },
    { id: 46, name: 'MDR Thüringen HD' },
    { id: 47, name: 'SR Fernsehen HD' },
    { id: 48, name: 'NDR FS MV HD' },
    { id: 49, name: 'N24 DOKU' },
    { id: 50, name: 'TOGGO plus' },
    { id: 51, name: 'NDR FS SH HD' },
    { id: 52, name: 'Sky Sport News HD' },
    { id: 53, name: 'ARD-alpha' },
    { id: 54, name: 'Zee One HD' },
    { id: 55, name: 'Bibel TV HD' },
    { id: 56, name: 'Welt der Wunder' },
    { id: 57, name: 'eo TV' },
    { id: 58, name: 'Juwelo HD' },
    { id: 59, name: 'Sky 1 HD' },
    { id: 60, name: '99 frei belegbar' },
    { id: 1, name: '9' },
    { id: 100, name: 'Sky 1 HD' },
    { id: 104, name: 'Sky Atlantic HD' },
    { id: 115, name: 'Fox HD' },
    { id: 116, name: 'TNT Serie HD' },
    { id: 118, name: 'SyFy HD' },
    { id: 119, name: '13th Street HD' },
    { id: 125, name: 'Universal TV HD' },
    { id: 127, name: 'TNT Comedy HD' },
    { id: 128, name: 'E! Entertainment HD' },
    { id: 131, name: 'Sky Krimi' },
    { id: 145, name: 'Romance TV' },
    { id: 161, name: 'Das Erste HD' },
    { id: 162, name: 'ZDF HD' },
    { id: 163, name: 'RTL HD' },
    { id: 164, name: 'SAT.1 HD' },
    { id: 165, name: 'ProSieben HD' },
    { id: 166, name: 'VOX HD' },
    { id: 167, name: 'RTLII HD' },
    { id: 168, name: 'kabel eins HD' },
    { id: 169, name: 'SIXX HD' },
    { id: 170, name: 'Sat.1 Gold HD' },
    { id: 171, name: 'ProSieben MAXX HD' },
    { id: 173, name: 'RTL Nitro HD' },
    { id: 174, name: 'TLC HD' },
    { id: 175, name: 'zdf_neo HD' },
    { id: 176, name: 'Servus TV HD DE' },
    { id: 177, name: 'Zee One HD' },
    { id: 181, name: 'Das Erste' },
    { id: 182, name: 'ZDF' },
    { id: 183, name: 'RTL' },
    { id: 184, name: 'Sat.1' },
    { id: 185, name: 'ProSieben' },
    { id: 186, name: 'VOX' },
    { id: 187, name: 'RTL2' },
    { id: 188, name: 'kabel eins' },
    { id: 189, name: 'SIXX' },
    { id: 190, name: 'Sat.1 Gold' },
    { id: 191, name: 'ProSieben MAXX' },
    { id: 192, name: 'RTL Plus' },
    { id: 193, name: 'RTL Nitro' },
    { id: 194, name: 'TLC' },
    { id: 195, name: 'zdf_neo' },
    { id: 196, name: 'Servus TV DE' },
    { id: 197, name: 'Zee One' },
    { id: 198, name: 'Comedy Central' },
    { id: 2, name: '10 HD' },
    { id: 200, name: 'Sky Sport News HD' },
    { id: 202, name: 'Sky Sport UHD' },
    { id: 210, name: 'Sky Sport Bundesliga UHD' },
    { id: 211, name: 'Sky Sport Bundesliga 1 HD' },
    { id: 212, name: '220 Bundesliga' },
    { id: 221, name: 'Sky Sport 1 HD' },
    { id: 222, name: 'Sky Sport 2 HD' },
    { id: 223, name: '231 Sky Sport' },
    { id: 235, name: 'Sky Sport Austria HD' },
    { id: 239, name: 'Eurosport 1 HD' },
    { id: 240, name: 'Eurosport 2 HD' },
    { id: 241, name: '246 Eurosport360HD 1-6' },
    { id: 247, name: '249 Eurosport360HD 7-9' },
    { id: 250, name: 'Sky Sport News' },
    { id: 251, name: 'Sky Sport Bundesliga 1' },
    { id: 252, name: '260 Sport Bundesliga 2-10' },
    { id: 261, name: 'Sky Sport 1' },
    { id: 262, name: 'Sky Sport 2' },
    { id: 263, name: '271 Sky Sport' },
    { id: 280, name: 'Sky Sport Austria' },
    { id: 281, name: 'Eurosport 1' },
    { id: 288, name: 'sportdigital HD' },
    { id: 290, name: 'SPORT1 HD' },
    { id: 291, name: 'SPORT1' },
    { id: 292, name: 'DAZN 1 Bar HD' },
    { id: 293, name: 'DAZN 2 Bar HD' },
    { id: 294, name: 'Eurosport 2 HD Xtra' },
    { id: 3, name: '11' },
    { id: 3, name: '11 HD' },
    { id: 300, name: 'Sky Cinema HD' },
    { id: 301, name: 'Sky Cinema +1 HD' },
    { id: 302, name: 'Sky Cinema +24 HD' },
    { id: 303, name: 'Sky Cinema Hits HD' },
    { id: 304, name: 'Sky Cinema Action HD' },
    { id: 305, name: 'Sky Cinema Family HD' },
    { id: 309, name: 'Disney Cinemagic HD' },
    { id: 312, name: 'TNT Film HD' },
    { id: 320, name: 'Sky Cinema' },
    { id: 321, name: 'Sky Cinema +1' },
    { id: 322, name: 'Sky Cinema +24' },
    { id: 323, name: 'Sky Cinema Hits' },
    { id: 324, name: 'Sky Cinema Action' },
    { id: 325, name: 'Sky Cinema Family' },
    { id: 326, name: 'Sky Cinema Comedy' },
    { id: 327, name: 'Sky Cinema Emotion' },
    { id: 328, name: 'Sky Cinema Nostalgie' },
    { id: 331, name: 'Heimatkanal' },
    { id: 333, name: 'Kinowelt TV' },
    { id: 340, name: 'Beate-Uhse.TV HD' },
    { id: 360, name: 'TELE 5 HD' },
    { id: 361, name: 'ANIXE HD' },
    { id: 365, name: 'TELE 5' },
    { id: 366, name: 'ANIXE SD' },
    { id: 367, name: 'tm3' },
    { id: 370, name: 'Sky Select' },
    { id: 375, name: '383 Sky Select' },
    { id: 384, name: 'Select Event A' },
    { id: 385, name: 'Select Event B' },
    { id: 390, name: 'Blue Movie' },
    { id: 391, name: '393 Blue Movie 1-3' },
    { id: 400, name: 'Sky Arts HD' },
    { id: 401, name: 'NatGeo HD' },
    { id: 402, name: 'NatGeo Wild HD' },
    { id: 405, name: 'SpiegelGeschichte HD' },
    { id: 407, name: 'History HD' },
    { id: 409, name: 'Discovery HD' },
    { id: 416, name: 'Spiegel TV Wissen' },
    { id: 417, name: 'Motorvision TV' },
    { id: 418, name: 'A&E' },
    { id: 460, name: 'arte HD' },
    { id: 461, name: 'One HD' },
    { id: 462, name: 'Phoenix HD' },
    { id: 463, name: '3sat HD' },
    { id: 464, name: 'ARD-alpha HD' },
    { id: 465, name: 'MB LIVE' },
    { id: 466, name: 'DMAX HD' },
    { id: 467, name: 'Insight HD' },
    { id: 468, name: 'Insight UHD' },
    { id: 469, name: 'UHD1 by ASTRA / HD+' },
    { id: 470, name: 'Travelxp 4k' },
    { id: 471, name: 'RTL UHD' },
    { id: 480, name: 'arte' },
    { id: 481, name: 'One' },
    { id: 482, name: 'Phoenix' },
    { id: 483, name: '3sat' },
    { id: 484, name: 'ARD-alpha' },
    { id: 485, name: 'DMAX' },
    { id: 486, name: 'CGTN Documentary' },
    { id: 487, name: 'Welt der Wunder' },
    { id: 488, name: 'Kabel Eins Doku' },
    { id: 489, name: 'N24 DOKU' },
    { id: 500, name: 'Disney XD' },
    { id: 501, name: 'Disney Junior HD' },
    { id: 523, name: 'Junior' },
    { id: 524, name: 'Boomerang' },
    { id: 525, name: 'Cartoon Network' },
    { id: 550, name: 'KiKa HD' },
    { id: 551, name: 'Super RTL HD' },
    { id: 552, name: 'Disney Channel HD' },
    { id: 553, name: 'NICK / MTV+ HD' },
    { id: 560, name: 'Super RTL' },
    { id: 561, name: 'Disney Channel' },
    { id: 562, name: 'KiKa' },
    { id: 563, name: 'Toggo Plus' },
    { id: 564, name: 'NICK / MTV+' },
    { id: 610, name: 'Jukebox' },
    { id: 615, name: 'Classica' },
    { id: 679, name: 'MTV HD' },
    { id: 680, name: 'Deluxe Music HD' },
    { id: 681, name: 'Deluxe Music' },
    { id: 683, name: 'MTV' },
    { id: 692, name: 'Folx TV' },
    { id: 693, name: 'gotv neu' },
    { id: 695, name: 'Melodie TV NEU' },
    { id: 696, name: 'Deutsches Musik Fern.' },
    { id: 701, name: 'Welt HD' },
    { id: 702, name: 'n-tv HD' },
    { id: 703, name: 'tagesschau24 HD' },
    { id: 704, name: 'ZDFinfo HD' },
    { id: 707, name: 'NHK World HD;JPN' },
    { id: 708, name: 'TRT World HD' },
    { id: 709, name: 'BBC World News HD' },
    { id: 710, name: 'Al Jazeera English HD' },
    { id: 711, name: 'Welt' },
    { id: 712, name: 'n-tv' },
    { id: 713, name: 'EURONEWS GERMAN' },
    { id: 714, name: 'tagesschau24' },
    { id: 715, name: 'ZDFinfo' },
    { id: 716, name: 'Deutsche Welle' },
    { id: 718, name: 'oe24.tv HD' },
    { id: 719, name: 'Sky News Intl.' },
    { id: 721, name: 'Bloomberg Europe TV' },
    { id: 722, name: 'CNBC Europe' },
    { id: 723, name: 'CNN Int.' },
    { id: 724, name: 'France 24 (in English)' },
    { id: 725, name: 'France' },
    { id: 726, name: 'EURONEWS FRENCH' },
    { id: 727, name: 'TV5 Monde Europe' },
    { id: 728, name: 'RAI News 24' },
    { id: 729, name: 'TRT Türk' },
    { id: 730, name: 'I24 NEWS' },
    { id: 731, name: 'Aragon TV INT' },
    { id: 732, name: 'BVN TV' },
    { id: 733, name: 'TV Record SD' },
    { id: 734, name: 'TVE INTL. EUROPA' },
    { id: 735, name: 'Russia Today' },
    { id: 736, name: 'Al Jazeera English' },
    { id: 737, name: 'Al Jazeera Channel' },
    { id: 738, name: 'Arirang TV' },
    { id: 739, name: 'CGTN F' },
    { id: 740, name: 'CGTN	751;ORF 1 HD' },
    { id: 752, name: 'ATV HD' },
    { id: 753, name: 'Servus TV HD Österreich' },
    { id: 754, name: 'ORF III HD' },
    { id: 755, name: 'ORF Sport+ HD' },
    { id: 756, name: 'PULS 4 HD Austria' },
    { id: 757, name: 'SAT.1 HD Austria' },
    { id: 758, name: 'RTL HD Austria' },
    { id: 759, name: 'Pro7 HD Austria' },
    { id: 760, name: 'VOX HD Austria' },
    { id: 761, name: 'Kabel 1 HD Austria' },
    { id: 762, name: 'RTL2 HD Austria' },
    { id: 763, name: 'WELT HD' },
    { id: 764, name: 'TELE 5 HD Austria' },
    { id: 765, name: 'DMAX HD Austria' },
    { id: 766, name: 'MTV HD Austria' },
    { id: 767, name: 'SAT.1 Gold HD Austria' },
    { id: 768, name: 'Pro7 MAXX HD Austria' },
    { id: 769, name: 'sixx HD Austria' },
    { id: 770, name: 'Deluxe Music HD Austria' },
    { id: 771, name: 'Disney Channel HD Austria' },
    { id: 772, name: 'PULS 4 Austria' },
    { id: 773, name: 'SAT.1 Austria' },
    { id: 774, name: 'RTL Austria' },
    { id: 775, name: 'PRO7 Austria' },
    { id: 776, name: 'VOX Austria' },
    { id: 777, name: 'sixx Austria' },
    { id: 778, name: 'Kabel 1 Austria' },
    { id: 779, name: 'RTL2 Austria' },
    { id: 780, name: 'SUPER RTL Austria' },
    { id: 781, name: 'ATV 2' },
    { id: 782, name: 'Pro7 MAXX Austria' },
    { id: 783, name: 'Sat.1 Gold Österreich' },
    { id: 784, name: 'NICKELODEON AT' },
    { id: 785, name: 'Comedy Central AT' },
    { id: 786, name: 'DMAX Austria' },
    { id: 787, name: 'NITRO Austria' },
    { id: 788, name: 'N24 Doku Austria' },
    { id: 789, name: 'Kabel1doku austria' },
    { id: 790, name: 'Schau TV HD' },
    { id: 791, name: 'n-tv austria' },
    { id: 792, name: 'RTLplus austria	800;BR Ferns. Nord HD' },
    { id: 801, name: 'BR Ferns. Süd HD' },
    { id: 802, name: 'NDR HH HD' },
    { id: 803, name: 'NDR MV HD' },
    { id: 804, name: 'NDR NDS HD' },
    { id: 805, name: 'NDR SH HD' },
    { id: 806, name: 'SWR BW HD' },
    { id: 807, name: 'SWR RP HD' },
    { id: 808, name: 'WDR HD Köln' },
    { id: 809, name: 'WDR HD Aachen' },
    { id: 810, name: 'WDR HD Bielefeld' },
    { id: 811, name: 'WDR HD Bonn' },
    { id: 812, name: 'WDR HD Dortmund' },
    { id: 813, name: 'WDR HD Duisburg' },
    { id: 814, name: 'WDR HD Düsseldorf' },
    { id: 815, name: 'WDR HD Essen' },
    { id: 816, name: 'WDR HD Münster' },
    { id: 817, name: 'WDR HD Siegen' },
    { id: 818, name: 'WDR HD Wuppertal' },
    { id: 819, name: 'hr-fernsehen HD' },
    { id: 820, name: 'MDR Sachsen HD' },
    { id: 821, name: 'MDR S-Anhalt HD' },
    { id: 822, name: 'MDR Thüringen HD' },
    { id: 823, name: 'rbb Berlin HD' },
    { id: 824, name: 'rbb Brandenburg HD' },
    { id: 825, name: 'SR Fernsehen HD' },
    { id: 826, name: 'Radio Bremen HD' },
    { id: 827, name: 'R9 Österreich HD' },
    { id: 828, name: 'münchen.tv HD' },
    { id: 829, name: 'Franken Ferns. HD' },
    { id: 830, name: 'a.tv HD' },
    { id: 831, name: 'Mainfranken HD' },
    { id: 832, name: 'TV Oberfranken HD' },
    { id: 833, name: 'TVA-OTV HD' },
    { id: 834, name: 'Niederbayern HD' },
    { id: 835, name: 'Ulm-Allgäu HD' },
    { id: 836, name: 'intv HD' },
    { id: 837, name: 'rfo regional OBB HD' },
    { id: 838, name: 'Oberpfalz TV HD	839;BR Fernsehen Nord' },
    { id: 840, name: 'BR Fernsehen Süd' },
    { id: 841, name: 'hr-fernsehen' },
    { id: 842, name: 'rhein main tv' },
    { id: 843, name: 'MDR Sachsen' },
    { id: 844, name: 'MDR S-Anhalt' },
    { id: 845, name: 'MDR Thüringen' },
    { id: 846, name: 'NDR FS HH' },
    { id: 847, name: 'NDR FS MV' },
    { id: 848, name: 'NDR FS NDS' },
    { id: 849, name: 'NDR FS SH' },
    { id: 850, name: 'Radio Bremen TV' },
    { id: 851, name: 'RTL HB NDS' },
    { id: 852, name: 'RTL Regional NRW' },
    { id: 853, name: 'rbb Berlin' },
    { id: 854, name: 'rbb Brandenburg' },
    { id: 855, name: 'SR Fernsehen' },
    { id: 856, name: 'SWR Fernsehen BW' },
    { id: 857, name: 'SWR Fernsehen RP' },
    { id: 858, name: 'L-TV/TVM' },
    { id: 859, name: 'WDR Köln' },
    { id: 860, name: 'WDR;Aachen' },
    { id: 861, name: 'WDR;Bielefeld' },
    { id: 862, name: 'WDR;Bonn' },
    { id: 863, name: 'WDR;Dortmund' },
    { id: 864, name: 'WDR;Duisburg' },
    { id: 865, name: 'WDR;Düsseldorf' },
    { id: 866, name: 'WDR;Essen' },
    { id: 867, name: 'WDR;Münster' },
    { id: 868, name: 'WDR;Siegen' },
    { id: 869, name: 'WDR;Wuppertal' },
    { id: 881, name: '889 ORF 2 HD' },
    { id: 890, name: '898 ORF 2 (SD)' },
    { id: 899, name: 'LT1-OOE' },
    { id: 900, name: 'QVC UHD' },
    { id: 901, name: 'QVC HD' },
    { id: 902, name: 'QVC 2 HD' },
    { id: 903, name: 'QVC Style HD' },
    { id: 904, name: 'HSE24 HD' },
    { id: 905, name: 'HSE24 Extra HD' },
    { id: 906, name: 'Juwelo HD' },
    { id: 907, name: 'pearl.tv HD Shop' },
    { id: 908, name: 'Channel21 HD' },
    { id: 909, name: '1-2-3.tv HD' },
    { id: 910, name: 'sonnenklar.TV HD' },
    { id: 911, name: 'Sparhandy TV 2 HD' },
    { id: 913, name: 'Bibel TV HD' },
    { id: 914, name: 'HOPE Channel HD' },
    { id: 920, name: 'QVC Deutschland' },
    { id: 921, name: 'QVC 2' },
    { id: 922, name: 'QVC Style' },
    { id: 923, name: 'HSE24' },
    { id: 924, name: 'HSE24 Extra' },
    { id: 925, name: 'HSE24 Trend' },
    { id: 926, name: 'meinTVshop' },
    { id: 927, name: 'Channel 21' },
    { id: 928, name: '1-2-3.tv' },
    { id: 929, name: 'MediaShop;Meine' },
    { id: 930, name: 'MediaShop;Neuheiten' },
    { id: 931, name: 'Immer etwas Neues TV' },
    { id: 932, name: 'Sparhandy TV' },
    { id: 933, name: 'Sparhandy TV 2' },
    { id: 934, name: 'e8 television' },
    { id: 935, name: 'Genius Plus' },
    { id: 936, name: 'Juwelo TV' },
    { id: 937, name: 'pearl.tv' },
    { id: 938, name: 'PEARL TV 4K UHD' },
    { id: 939, name: 'Fashion 4K' },
    { id: 940, name: 'Sonnenklar TV' },
    { id: 962, name: 'AstroTV' },
    { id: 970, name: 'Bibel TV' },
    { id: 971, name: 'GOD Channel' },
    { id: 972, name: 'EWTN katholisches TV' },
    { id: 973, name: 'K-TV' },
    { id: 974, name: 'Sophia TV' },
    { id: 975, name: 'Sonlife Broadcast Network' },
    { id: 980, name: 'health.tv' },
    { id: 981, name: 'eoTV' },
    { id: 982, name: 'RiC' },
    { id: 998, name: 'STEST1' },
    { id: 999, name: 'STEST2' },
  ];
  constructor() {}

  ngOnInit(): void {}
}
