import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of } from 'rxjs';
import { map, catchError } from 'rxjs/operators';

@Injectable({
  providedIn: 'root',
})
export class ChannelsService {
  constructor(private httpClient: HttpClient) {}

  CHANNELS = [
    { channel: 1, name: 'Das Erste HD ' },
    { channel: 2, name: 'ZDF HD' },
    { channel: 3, name: 'RTL Television ' },
    { channel: 4, name: 'SAT.1' },
    { channel: 5, name: 'VOX' },
    { channel: 6, name: 'ProSieben ' },
    { channel: 7, name: 'kabel eins ' },
    { channel: 8, name: 'RTL2' },
    { channel: 9, name: 'zdf_neo HD' },
    { channel: 10, name: 'WDR HD Köln' },
    { channel: 11, name: 'BR FS Süd HD' },
    { channel: 12, name: 'SUPER RTL' },
    { channel: 13, name: 'NITRO' },
    { channel: 14, name: 'NDR FS NDS HD' },
    { channel: 15, name: 'SAT.1 Gold' },
    { channel: 16, name: '3sat HD' },
    { channel: 17, name: 'MDR S-Anhalt HD' },
    { channel: 18, name: 'ZDFinfo HD' },
    { channel: 19, name: 'RTLplus' },
    { channel: 20, name: 'arte HD' },
    { channel: 21, name: 'n-tv' },
    { channel: 22, name: 'hr-fernsehen HD' },
    { channel: 23, name: 'PHOENIX HD' },
    { channel: 24, name: 'rbb Berlin HD' },
    { channel: 25, name: 'KiKA HD' },
    { channel: 26, name: 'DMAX' },
    { channel: 27, name: 'WELT' },
    { channel: 28, name: 'SWR BW HD' },
    { channel: 29, name: 'Disney Channel' },
    { channel: 30, name: 'SPORT 1' },
    { channel: 31, name: 'TELE 5' },
    { channel: 32, name: 'SIXX' },
    { channel: 33, name: 'Pro7 MAXX' },
    { channel: 34, name: 'SWR RP HD' },
    { channel: 35, name: 'ONE HD' },
    { channel: 36, name: 'Eurosport 1 DE' },
    { channel: 37, name: 'MDR Sachsen HD' },
    { channel: 38, name: 'kabel eins Doku' },
    { channel: 39, name: 'TLC' },
    { channel: 40, name: 'tagesschau24 HD' },
    { channel: 41, name: 'Servus TV HD DE' },
    { channel: 42, name: 'Radio Bremen TV' },
    { channel: 43, name: 'DELUXE MUSIC' },
    { channel: 44, name: 'NDR FS HH HD' },
    { channel: 45, name: 'rbb BrandenburgHD' },
    { channel: 46, name: 'MDR Thüringen HD' },
    { channel: 47, name: 'SR Fernsehen HD' },
    { channel: 48, name: 'NDR FS MV HD' },
    { channel: 49, name: 'N24 DOKU' },
    { channel: 50, name: 'TOGGO plus' },
    { channel: 51, name: 'NDR FS SH HD' },
    { channel: 52, name: 'Sky Sport News HD' },
    { channel: 53, name: 'ARD-alpha' },
    { channel: 54, name: 'Zee One HD' },
    { channel: 55, name: 'Bibel TV HD' },
    { channel: 56, name: 'Welt der Wunder' },
    { channel: 57, name: 'eo TV' },
    { channel: 58, name: 'Juwelo HD' },
    { channel: 59, name: 'Sky 1 HD' },
    { channel: 60, name: 'Frei belegbar' },
    { channel: 100, name: 'Sky 1 HD' },
    { channel: 104, name: 'Sky Atlantic HD' },
    { channel: 115, name: 'Fox HD' },
    { channel: 116, name: 'TNT Serie HD' },
    { channel: 118, name: 'SyFy HD' },
    { channel: 119, name: '13th Street HD' },
    { channel: 125, name: 'Universal TV HD' },
    { channel: 127, name: 'TNT Comedy HD' },
    { channel: 128, name: 'E! Entertainment HD' },
    { channel: 131, name: 'Sky Krimi' },
    { channel: 145, name: 'Romance TV' },
    { channel: 161, name: 'Das Erste HD' },
    { channel: 162, name: 'ZDF HD' },
    { channel: 163, name: 'RTL HD' },
    { channel: 164, name: 'SAT.1 HD' },
    { channel: 165, name: 'ProSieben HD' },
    { channel: 166, name: 'VOX HD' },
    { channel: 167, name: 'RTLII HD' },
    { channel: 168, name: 'kabel eins HD' },
    { channel: 169, name: 'SIXX HD' },
    { channel: 170, name: 'Sat.1 Gold HD' },
    { channel: 171, name: 'ProSieben MAXX HD' },
    { channel: 173, name: 'RTL Nitro HD' },
    { channel: 174, name: 'TLC HD' },
    { channel: 175, name: 'zdf_neo HD' },
    { channel: 176, name: 'Servus TV HD DE' },
    { channel: 177, name: 'Zee One HD' },
    { channel: 181, name: 'Das Erste' },
    { channel: 182, name: 'ZDF' },
    { channel: 183, name: 'RTL' },
    { channel: 184, name: 'Sat.1' },
    { channel: 185, name: 'ProSieben' },
    { channel: 186, name: 'VOX' },
    { channel: 187, name: 'RTL2' },
    { channel: 188, name: 'kabel eins' },
    { channel: 189, name: 'SIXX' },
    { channel: 190, name: 'Sat.1 Gold' },
    { channel: 191, name: 'ProSieben MAXX' },
    { channel: 192, name: 'RTL Plus' },
    { channel: 193, name: 'RTL Nitro' },
    { channel: 194, name: 'TLC' },
    { channel: 195, name: 'zdf_neo' },
    { channel: 196, name: 'Servus TV DE' },
    { channel: 197, name: 'Zee One' },
    { channel: 198, name: 'Comedy Central' },
    { channel: 200, name: 'Sky Sport News HD' },
    { channel: 202, name: 'Sky Sport UHD' },
    { channel: 210, name: 'Sky Sport Bundesliga UHD' },
    { channel: 211, name: 'Sky Sport Bundesliga 1 HD' },
    { channel: 212, name: '220 Bundesliga' },
    { channel: 221, name: 'Sky Sport 1 HD' },
    { channel: 222, name: 'Sky Sport 2 HD' },
    { channel: 223, name: '231 Sky Sport' },
    { channel: 235, name: 'Sky Sport Austria HD' },
    { channel: 239, name: 'Eurosport 1 HD' },
    { channel: 240, name: 'Eurosport 2 HD' },
    { channel: 241, name: '246 Eurosport360HD 1-6' },
    { channel: 247, name: '249 Eurosport360HD 7-9' },
    { channel: 250, name: 'Sky Sport News' },
    { channel: 251, name: 'Sky Sport Bundesliga 1' },
    { channel: 252, name: '260 Sport Bundesliga 2-10' },
    { channel: 261, name: 'Sky Sport 1' },
    { channel: 262, name: 'Sky Sport 2' },
    { channel: 263, name: '271 Sky Sport' },
    { channel: 280, name: 'Sky Sport Austria' },
    { channel: 281, name: 'Eurosport 1' },
    { channel: 288, name: 'sportdigital HD' },
    { channel: 290, name: 'SPORT1 HD' },
    { channel: 291, name: 'SPORT1' },
    { channel: 292, name: 'DAZN 1 Bar HD' },
    { channel: 293, name: 'DAZN 2 Bar HD' },
    { channel: 294, name: 'Eurosport 2 HD Xtra' },
    { channel: 300, name: 'Sky Cinema HD' },
    { channel: 301, name: 'Sky Cinema +1 HD' },
    { channel: 302, name: 'Sky Cinema +24 HD' },
    { channel: 303, name: 'Sky Cinema Hits HD' },
    { channel: 304, name: 'Sky Cinema Action HD' },
    { channel: 305, name: 'Sky Cinema Family HD' },
    { channel: 309, name: 'Disney Cinemagic HD' },
    { channel: 312, name: 'TNT Film HD' },
    { channel: 320, name: 'Sky Cinema' },
    { channel: 321, name: 'Sky Cinema +1' },
    { channel: 322, name: 'Sky Cinema +24' },
    { channel: 323, name: 'Sky Cinema Hits' },
    { channel: 324, name: 'Sky Cinema Action' },
    { channel: 325, name: 'Sky Cinema Family' },
    { channel: 326, name: 'Sky Cinema Comedy' },
    { channel: 327, name: 'Sky Cinema Emotion' },
    { channel: 328, name: 'Sky Cinema Nostalgie' },
    { channel: 331, name: 'Heimatkanal' },
    { channel: 333, name: 'Kinowelt TV' },
    { channel: 340, name: 'Beate-Uhse.TV HD' },
    { channel: 360, name: 'TELE 5 HD' },
    { channel: 361, name: 'ANIXE HD' },
    { channel: 365, name: 'TELE 5' },
    { channel: 366, name: 'ANIXE SD' },
    { channel: 367, name: 'tm3' },
    { channel: 370, name: 'Sky Select' },
    { channel: 375, name: '383 Sky Select' },
    { channel: 384, name: 'Select Event A' },
    { channel: 385, name: 'Select Event B' },
    { channel: 390, name: 'Blue Movie' },
    { channel: 391, name: '393 Blue Movie 1-3' },
    { channel: 400, name: 'Sky Arts HD' },
    { channel: 401, name: 'NatGeo HD' },
    { channel: 402, name: 'NatGeo Wild HD' },
    { channel: 405, name: 'SpiegelGeschichte HD' },
    { channel: 407, name: 'History HD' },
    { channel: 409, name: 'Discovery HD' },
    { channel: 416, name: 'Spiegel TV Wissen' },
    { channel: 417, name: 'Motorvision TV' },
    { channel: 418, name: 'A&E' },
    { channel: 460, name: 'arte HD' },
    { channel: 461, name: 'One HD' },
    { channel: 462, name: 'Phoenix HD' },
    { channel: 463, name: '3sat HD' },
    { channel: 464, name: 'ARD-alpha HD' },
    { channel: 465, name: 'MB LIVE' },
    { channel: 466, name: 'DMAX HD' },
    { channel: 467, name: 'Insight HD' },
    { channel: 468, name: 'Insight UHD' },
    { channel: 469, name: 'UHD1 by ASTRA / HD+' },
    { channel: 470, name: 'Travelxp 4k' },
    { channel: 471, name: 'RTL UHD' },
    { channel: 480, name: 'arte' },
    { channel: 481, name: 'One' },
    { channel: 482, name: 'Phoenix' },
    { channel: 483, name: '3sat' },
    { channel: 484, name: 'ARD-alpha' },
    { channel: 485, name: 'DMAX' },
    { channel: 486, name: 'CGTN Documentary' },
    { channel: 487, name: 'Welt der Wunder' },
    { channel: 488, name: 'Kabel Eins Doku' },
    { channel: 489, name: 'N24 DOKU' },
    { channel: 500, name: 'Disney XD' },
    { channel: 501, name: 'Disney Junior HD' },
    { channel: 523, name: 'Junior' },
    { channel: 524, name: 'Boomerang' },
    { channel: 525, name: 'Cartoon Network' },
    { channel: 550, name: 'KiKa HD' },
    { channel: 551, name: 'Super RTL HD' },
    { channel: 552, name: 'Disney Channel HD' },
    { channel: 553, name: 'NICK / MTV+ HD' },
    { channel: 560, name: 'Super RTL' },
    { channel: 561, name: 'Disney Channel' },
    { channel: 562, name: 'KiKa' },
    { channel: 563, name: 'Toggo Plus' },
    { channel: 564, name: 'NICK / MTV+' },
    { channel: 610, name: 'Jukebox' },
    { channel: 615, name: 'Classica' },
    { channel: 679, name: 'MTV HD' },
    { channel: 680, name: 'Deluxe Music HD' },
    { channel: 681, name: 'Deluxe Music' },
    { channel: 683, name: 'MTV' },
    { channel: 692, name: 'Folx TV' },
    { channel: 693, name: 'gotv neu' },
    { channel: 695, name: 'Melodie TV NEU' },
    { channel: 696, name: 'Deutsches Musik Fern.' },
    { channel: 701, name: 'Welt HD' },
    { channel: 702, name: 'n-tv HD' },
    { channel: 703, name: 'tagesschau24 HD' },
    { channel: 704, name: 'ZDFinfo HD' },
    { channel: 707, name: 'NHK World HD;JPN' },
    { channel: 708, name: 'TRT World HD' },
    { channel: 709, name: 'BBC World News HD' },
    { channel: 710, name: 'Al Jazeera English HD' },
    { channel: 711, name: 'Welt' },
    { channel: 712, name: 'n-tv' },
    { channel: 713, name: 'EURONEWS GERMAN' },
    { channel: 714, name: 'tagesschau24' },
    { channel: 715, name: 'ZDFinfo' },
    { channel: 716, name: 'Deutsche Welle' },
    { channel: 718, name: 'oe24.tv HD' },
    { channel: 719, name: 'Sky News Intl.' },
    { channel: 721, name: 'Bloomberg Europe TV' },
    { channel: 722, name: 'CNBC Europe' },
    { channel: 723, name: 'CNN Int.' },
    { channel: 724, name: 'France 24 (in English)' },
    { channel: 725, name: 'France' },
    { channel: 726, name: 'EURONEWS FRENCH' },
    { channel: 727, name: 'TV5 Monde Europe' },
    { channel: 728, name: 'RAI News 24' },
    { channel: 729, name: 'TRT Türk' },
    { channel: 730, name: 'I24 NEWS' },
    { channel: 731, name: 'Aragon TV INT' },
    { channel: 732, name: 'BVN TV' },
    { channel: 733, name: 'TV Record SD' },
    { channel: 734, name: 'TVE INTL. EUROPA' },
    { channel: 735, name: 'Russia Today' },
    { channel: 736, name: 'Al Jazeera English' },
    { channel: 737, name: 'Al Jazeera Channel' },
    { channel: 738, name: 'Arirang TV' },
    { channel: 739, name: 'CGTN F' },
    { channel: 740, name: 'CGTN	751;ORF 1 HD' },
    { channel: 752, name: 'ATV HD' },
    { channel: 753, name: 'Servus TV HD Österreich' },
    { channel: 754, name: 'ORF III HD' },
    { channel: 755, name: 'ORF Sport+ HD' },
    { channel: 756, name: 'PULS 4 HD Austria' },
    { channel: 757, name: 'SAT.1 HD Austria' },
    { channel: 758, name: 'RTL HD Austria' },
    { channel: 759, name: 'Pro7 HD Austria' },
    { channel: 760, name: 'VOX HD Austria' },
    { channel: 761, name: 'Kabel 1 HD Austria' },
    { channel: 762, name: 'RTL2 HD Austria' },
    { channel: 763, name: 'WELT HD' },
    { channel: 764, name: 'TELE 5 HD Austria' },
    { channel: 765, name: 'DMAX HD Austria' },
    { channel: 766, name: 'MTV HD Austria' },
    { channel: 767, name: 'SAT.1 Gold HD Austria' },
    { channel: 768, name: 'Pro7 MAXX HD Austria' },
    { channel: 769, name: 'sixx HD Austria' },
    { channel: 770, name: 'Deluxe Music HD Austria' },
    { channel: 771, name: 'Disney Channel HD Austria' },
    { channel: 772, name: 'PULS 4 Austria' },
    { channel: 773, name: 'SAT.1 Austria' },
    { channel: 774, name: 'RTL Austria' },
    { channel: 775, name: 'PRO7 Austria' },
    { channel: 776, name: 'VOX Austria' },
    { channel: 777, name: 'sixx Austria' },
    { channel: 778, name: 'Kabel 1 Austria' },
    { channel: 779, name: 'RTL2 Austria' },
    { channel: 780, name: 'SUPER RTL Austria' },
    { channel: 781, name: 'ATV 2' },
    { channel: 782, name: 'Pro7 MAXX Austria' },
    { channel: 783, name: 'Sat.1 Gold Österreich' },
    { channel: 784, name: 'NICKELODEON AT' },
    { channel: 785, name: 'Comedy Central AT' },
    { channel: 786, name: 'DMAX Austria' },
    { channel: 787, name: 'NITRO Austria' },
    { channel: 788, name: 'N24 Doku Austria' },
    { channel: 789, name: 'Kabel1doku austria' },
    { channel: 790, name: 'Schau TV HD' },
    { channel: 791, name: 'n-tv austria' },
    { channel: 792, name: 'RTLplus austria	800;BR Ferns. Nord HD' },
    { channel: 801, name: 'BR Ferns. Süd HD' },
    { channel: 802, name: 'NDR HH HD' },
    { channel: 803, name: 'NDR MV HD' },
    { channel: 804, name: 'NDR NDS HD' },
    { channel: 805, name: 'NDR SH HD' },
    { channel: 806, name: 'SWR BW HD' },
    { channel: 807, name: 'SWR RP HD' },
    { channel: 808, name: 'WDR HD Köln' },
    { channel: 809, name: 'WDR HD Aachen' },
    { channel: 810, name: 'WDR HD Bielefeld' },
    { channel: 811, name: 'WDR HD Bonn' },
    { channel: 812, name: 'WDR HD Dortmund' },
    { channel: 813, name: 'WDR HD Duisburg' },
    { channel: 814, name: 'WDR HD Düsseldorf' },
    { channel: 815, name: 'WDR HD Essen' },
    { channel: 816, name: 'WDR HD Münster' },
    { channel: 817, name: 'WDR HD Siegen' },
    { channel: 818, name: 'WDR HD Wuppertal' },
    { channel: 819, name: 'hr-fernsehen HD' },
    { channel: 820, name: 'MDR Sachsen HD' },
    { channel: 821, name: 'MDR S-Anhalt HD' },
    { channel: 822, name: 'MDR Thüringen HD' },
    { channel: 823, name: 'rbb Berlin HD' },
    { channel: 824, name: 'rbb Brandenburg HD' },
    { channel: 825, name: 'SR Fernsehen HD' },
    { channel: 826, name: 'Radio Bremen HD' },
    { channel: 827, name: 'R9 Österreich HD' },
    { channel: 828, name: 'münchen.tv HD' },
    { channel: 829, name: 'Franken Ferns. HD' },
    { channel: 830, name: 'a.tv HD' },
    { channel: 831, name: 'Mainfranken HD' },
    { channel: 832, name: 'TV Oberfranken HD' },
    { channel: 833, name: 'TVA-OTV HD' },
    { channel: 834, name: 'Niederbayern HD' },
    { channel: 835, name: 'Ulm-Allgäu HD' },
    { channel: 836, name: 'intv HD' },
    { channel: 837, name: 'rfo regional OBB HD' },
    { channel: 838, name: 'Oberpfalz TV HD	839;BR Fernsehen Nord' },
    { channel: 840, name: 'BR Fernsehen Süd' },
    { channel: 841, name: 'hr-fernsehen' },
    { channel: 842, name: 'rhein main tv' },
    { channel: 843, name: 'MDR Sachsen' },
    { channel: 844, name: 'MDR S-Anhalt' },
    { channel: 845, name: 'MDR Thüringen' },
    { channel: 846, name: 'NDR FS HH' },
    { channel: 847, name: 'NDR FS MV' },
    { channel: 848, name: 'NDR FS NDS' },
    { channel: 849, name: 'NDR FS SH' },
    { channel: 850, name: 'Radio Bremen TV' },
    { channel: 851, name: 'RTL HB NDS' },
    { channel: 852, name: 'RTL Regional NRW' },
    { channel: 853, name: 'rbb Berlin' },
    { channel: 854, name: 'rbb Brandenburg' },
    { channel: 855, name: 'SR Fernsehen' },
    { channel: 856, name: 'SWR Fernsehen BW' },
    { channel: 857, name: 'SWR Fernsehen RP' },
    { channel: 858, name: 'L-TV/TVM' },
    { channel: 859, name: 'WDR Köln' },
    { channel: 860, name: 'WDR;Aachen' },
    { channel: 861, name: 'WDR;Bielefeld' },
    { channel: 862, name: 'WDR;Bonn' },
    { channel: 863, name: 'WDR;Dortmund' },
    { channel: 864, name: 'WDR;Duisburg' },
    { channel: 865, name: 'WDR;Düsseldorf' },
    { channel: 866, name: 'WDR;Essen' },
    { channel: 867, name: 'WDR;Münster' },
    { channel: 868, name: 'WDR;Siegen' },
    { channel: 869, name: 'WDR;Wuppertal' },
    { channel: 881, name: '889 ORF 2 HD' },
    { channel: 890, name: '898 ORF 2 (SD)' },
    { channel: 899, name: 'LT1-OOE' },
    { channel: 900, name: 'QVC UHD' },
    { channel: 901, name: 'QVC HD' },
    { channel: 902, name: 'QVC 2 HD' },
    { channel: 903, name: 'QVC Style HD' },
    { channel: 904, name: 'HSE24 HD' },
    { channel: 905, name: 'HSE24 Extra HD' },
    { channel: 906, name: 'Juwelo HD' },
    { channel: 907, name: 'pearl.tv HD Shop' },
    { channel: 908, name: 'Channel21 HD' },
    { channel: 909, name: '1-2-3.tv HD' },
    { channel: 910, name: 'sonnenklar.TV HD' },
    { channel: 911, name: 'Sparhandy TV 2 HD' },
    { channel: 913, name: 'Bibel TV HD' },
    { channel: 914, name: 'HOPE Channel HD' },
    { channel: 920, name: 'QVC Deutschland' },
    { channel: 921, name: 'QVC 2' },
    { channel: 922, name: 'QVC Style' },
    { channel: 923, name: 'HSE24' },
    { channel: 924, name: 'HSE24 Extra' },
    { channel: 925, name: 'HSE24 Trend' },
    { channel: 926, name: 'meinTVshop' },
    { channel: 927, name: 'Channel 21' },
    { channel: 928, name: '1-2-3.tv' },
    { channel: 929, name: 'MediaShop;Meine' },
    { channel: 930, name: 'MediaShop;Neuheiten' },
    { channel: 931, name: 'Immer etwas Neues TV' },
    { channel: 932, name: 'Sparhandy TV' },
    { channel: 933, name: 'Sparhandy TV 2' },
    { channel: 934, name: 'e8 television' },
    { channel: 935, name: 'Genius Plus' },
    { channel: 936, name: 'Juwelo TV' },
    { channel: 937, name: 'pearl.tv' },
    { channel: 938, name: 'PEARL TV 4K UHD' },
    { channel: 939, name: 'Fashion 4K' },
    { channel: 940, name: 'Sonnenklar TV' },
    { channel: 962, name: 'AstroTV' },
    { channel: 970, name: 'Bibel TV' },
    { channel: 971, name: 'GOD Channel' },
    { channel: 972, name: 'EWTN katholisches TV' },
    { channel: 973, name: 'K-TV' },
    { channel: 974, name: 'Sophia TV' },
    { channel: 975, name: 'Sonlife Broadcast Network' },
    { channel: 980, name: 'health.tv' },
    { channel: 981, name: 'eoTV' },
    { channel: 982, name: 'RiC' },
    { channel: 998, name: 'STEST1' },
    { channel: 999, name: 'STEST2' },
  ];
}
